# Generated by Django 4.0.1 on 2022-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
