# Generated by Django 4.0.1 on 2022-05-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_donor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='adhaar_card',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='pan_card',
            field=models.CharField(default='', max_length=50),
        ),
    ]
